### PR TITLE
User type model

### LINKED ISSUE #11: create separate user type model
Create a UserType model with the following fields:
- id
- user_type

### PR DESCRIPTION
**Pull request by omolojakazeem**
Added the user_type app and created the UserType model

Fixes #11

### CODE REVIEW

**Comment by omolojakazeem** [comment]
I think this model should have been in the same app as the Accounts/Users app. or do you think it's ok as a separate App?

**Comment by Nkoli** [comment]
> Added the user_type app and created the UserType model
> 
> Fixes #11

why's the name of the app "user_type"?

**Comment by Nkoli** [comment]
> I think this model should have been in the same app as the Accounts/Users app. or do you think it's ok as a separate App?

never worked with multitenant apps, but if it's supposed to be a monolith, why do we need to separate them into different apps?

**Comment by omolojakazeem** [comment]
> > Added the user_type app and created the UserType model
> > Fixes #11
> 
> why's the name of the app "user_type"?

I was of the opinion of having separate apps for different purposes (Models). Except extremely related models that can be together in same model file. Nonetheless, I will go with having same app for all the models now. so I will rename the app to something more relatable.

**Pull request closed without merging**
